### ISSUE TITLE
Inspect pop-up

### ISSUE THREAD

**Issue by ayushpatnaikgit** [Douile/Chrome-Audio-Visualizer#3]
Even in developer option, inspect pop-up option seems to be disabled. I tried on different computers, tried both chrome and chromium. Other extensions are working perfectly fine. 

Thanks, 
Ayush, ayushpatnaik@gmail.com

**Comment by Douile** [comment]
This is because there is no popup. The browser action is handled in background.js as this seems to be the only way I could get permissions for browserCapture.
